### ISSUE TITLE
Unable to install after successful make

### ISSUE THREAD

**Issue by DirkSchueler** [X3n0m0rph59/eruption#113]
Using Ubuntu 21.10 I was able to run "make", but "sudo make install" led to
`Shutting down daemons from previous installations...
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
make: [Makefile:32: install] Error 1 (ignored)
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
make: [Makefile:33: install] Error 1 (ignored)
Created symlink /etc/systemd/system/eruption.service → /dev/null.
Unit /etc/systemd/system/eruption.service is masked, ignoring.
Commencing installation of Eruption...
cp: cannot stat 'target/release/eruption{,ctl,-cmd,-hwutil,-netfx,-debug-tool,-hotplug-helper,-gui,-audio-proxy,-process-monitor}': No such file or directory
make: *** [Makefile:118: install] Error 1`

Before everthing went fine whenwever I processed 
`cargo build --all --release

sudo mkdir -p "/etc/eruption"
sudo mkdir -p "/usr/share/doc/eruption"
sudo mkdir -p /usr/share/eruption/scripts/{lib/{macros,themes,hwdevices/{keyboards,mice}},examples}

sudo mkdir -p "/usr/share/applications"
sudo mkdir -p "/usr/share/icons/hicolor/64x64/apps"
sudo mkdir -p "/usr/share/eruption-gui/schemas"
sudo mkdir -p "/var/lib/eruption/profiles"
sudo mkdir -p "/usr/lib/systemd/system"
sudo mkdir -p "/usr/lib/systemd/system-preset"
sudo mkdir -p "/usr/lib/systemd/user"
sudo mkdir -p "/usr/lib/systemd/user-preset"
sudo mkdir -p "/usr/lib/systemd/system-sleep"
sudo mkdir -p "/usr/lib/udev/rules.d/"
sudo mkdir -p "/usr/share/dbus-1/system.d"
sudo mkdir -p "/usr/share/dbus-1/session.d"
sudo mkdir -p "/usr/share/polkit-1/actions"
sudo mkdir -p "/usr/share/man/man8"
sudo mkdir -p "/usr/share/man/man5"
sudo mkdir -p "/usr/share/man/man1"
sudo mkdir -p "/usr/share/bash-completion/completions"
sudo mkdir -p "/usr/share/fish/completions"
sudo mkdir -p "/usr/share/zsh/site-functions"
sudo mkdir -p "/usr/share/eruption/i18n"
sudo mkdir -p "/usr/share/eruption/sfx"

sudo cp "support/assets/eruption-gui/eruption-gui.desktop" "/usr/share/applications/"
sudo cp "support/assets/eruption-gui/eruption-gui.png" "/usr/share/icons/hicolor/64x64/apps/"
sudo cp "eruption-gui/schemas/gschemas.compiled" "/usr/share/eruption-gui/schemas/"
sudo cp "support/systemd/eruption-suspend.sh" "/usr/lib/systemd/system-sleep/eruption"
sudo cp "support/config/eruption.conf" "/etc/eruption/"
sudo cp "support/config/process-monitor.conf" "/etc/eruption/"
sudo cp "support/systemd/eruption.service" "/usr/lib/systemd/system/"
sudo cp "support/systemd/eruption.preset" "/usr/lib/systemd/system-preset/50-eruption.preset"
sudo cp "support/systemd/eruption-process-monitor.service" "/usr/lib/systemd/user/"
sudo cp "support/systemd/eruption-process-monitor.preset" "/usr/lib/systemd/user-preset/50-eruption-process-monitor.preset"
sudo cp "support/udev/99-eruption.rules" "/usr/lib/udev/rules.d/"
sudo cp "support/dbus/org.eruption.control.conf" "/usr/share/dbus-1/system.d/"
sudo cp "support/dbus/org.eruption.process_monitor.conf" "/usr/share/dbus-1/session.d/"
sudo cp "support/policykit/org.eruption.policy" "/usr/share/polkit-1/actions/"
sudo cp "support/man/eruption.8" "/usr/share/man/man8/"
sudo cp "support/man/eruption.conf.5" "/usr/share/man/man5/"
sudo cp "support/man/process-monitor.conf.5" "/usr/share/man/man5/"
sudo cp "support/man/eruptionctl.1" "/usr/share/man/man1/"
sudo cp "support/man/eruption-netfx.1" "/usr/share/man/man1/"
sudo cp "support/man/eruption-process-monitor.1" "/usr/share/man/man1/"

sudo cp "support/shell/completions/en_US/eruption-debug-tool.bash-completion" "/usr/share/bash-completion/completions/eruption-debug-tool"
sudo cp "support/shell/completions/en_US/eruption-netfx.bash-completion" "/usr/share/bash-completion/completions/eruption-netfx"
sudo cp "support/shell/completions/en_US/eruption-process-monitor.bash-completion" "/usr/share/bash-completion/completions/eruption-process-monitor"
sudo cp "support/shell/completions/en_US/eruptionctl.bash-completion" "/usr/share/bash-completion/completions/eruptionctl"

sudo cp "support/shell/completions/en_US/eruption-debug-tool.fish-completion" "/usr/share/fish/completions/eruption-debug-tool.fish"
sudo cp "support/shell/completions/en_US/eruption-netfx.fish-completion" "/usr/share/fish/completions/eruption-netfx.fish"
sudo cp "support/shell/completions/en_US/eruption-process-monitor.fish-completion" "/usr/share/fish/completions/eruption-process-monitor.fish"
sudo cp "support/shell/completions/en_US/eruptionctl.fish-completion" "/usr/share/fish/completions/eruptionctl.fish"

sudo cp "support/shell/completions/en_US/eruption-debug-tool.zsh-completion" "/usr/share/zsh/site-functions/_eruption-debug-tool"
sudo cp "support/shell/completions/en_US/eruption-netfx.zsh-completion" "/usr/share/zsh/site-functions/_eruption-netfx"
sudo cp "support/shell/completions/en_US/eruption-process-monitor.zsh-completion" "/usr/share/zsh/site-functions/_eruption-process-monitor"
sudo cp "support/shell/completions/en_US/eruptionctl.zsh-completion" "/usr/share/zsh/site-functions/_eruptionctl"

sudo cp "support/sfx/typewriter1.wav" "/usr/share/eruption/sfx/"
sudo cp "support/sfx/phaser1.wav" "/usr/share/eruption/sfx/"
sudo cp "support/sfx/phaser2.wav" "/usr/share/eruption/sfx/"

# Set file modes
sudo chmod 0755 /usr/lib/systemd/system-sleep/eruption

# Create required symlinks
sudo ln -s "phaser1.wav" "/usr/share/eruption/sfx/key-down.wav"
sudo ln -s "phaser2.wav" "/usr/share/eruption/sfx/key-up.wav"

sudo systemctl stop eruption.service

sudo cp target/release/eruption{,ctl,-netfx,-debug-tool,-gui,-process-monitor} /usr/bin/ && sudo setcap CAP_NET_ADMIN+ep /usr/bin/eruption-process-monitor

sudo cp -r eruption/src/scripts/* /usr/share/eruption/scripts/
sudo cp -r support/profiles/* /var/lib/eruption/profiles/

sudo systemctl daemon-reload
sudo systemctl start eruption.service
`
But even this way no longer works

**Comment by X3n0m0rph59** [comment]
Hi @DirkSchueler, looks like the directory `target/release/` does not contain the compiled binaries. The other error messages can be safely ignored. Could you please post the output of:

```sh
ls -alh target/release/
```

**Comment by X3n0m0rph59** [comment]
> Unit /etc/systemd/system/eruption.service is masked

To unmask `eruption.service` you may want to run this command:

```sh
sudo systemctl unmask eruption.service && sudo systemctl restart eruption.service
```

**Comment by DirkSchueler** [comment]
> Hi @DirkSchueler, looks like the directory `target/release/` does not contain the compiled binaries. The other error messages can be safely ignored. Could you please post the output of:
> 
> ```shell
> ls -alh target/release/
> ```

`total 42M
drwxrwxr-x    7 dirk dirk 4,0K Feb 28 12:23 .
drwxrwxr-x    4 dirk dirk 4,0K Mär 23  2021 ..
drwxrwxr-x 1750 dirk dirk 100K Feb 27 14:08 build
-rw-rw-r--    1 dirk dirk    0 Mär 23  2021 .cargo-lock
drwxrwxr-x    2 dirk dirk 772K Feb 28 12:23 deps
-rwxrwxr-x    2 dirk dirk 6,3M Feb 25 14:32 eruption
-rwxrwxr-x    2 dirk dirk 2,6M Feb 25 14:30 eruption-audio-proxy
-rw-rw-r--    1 dirk dirk  622 Feb 25 14:33 eruption-audio-proxy.d
-rwxrwxr-x    2 dirk dirk 2,3M Feb 25 14:30 eruption-cmd
-rw-rw-r--    1 dirk dirk  341 Feb  9 11:27 eruption-cmd.d
-rwxrwxr-x    2 dirk dirk 3,6M Feb 25 14:31 eruptionctl
-rw-rw-r--    1 dirk dirk  546 Nov 23 13:49 eruptionctl.d
-rw-rw-r--    1 dirk dirk 3,2K Feb 28 12:14 eruption.d
-rwxrwxr-x    2 dirk dirk 3,0M Feb 25 14:30 eruption-debug-tool
-rw-rw-r--    1 dirk dirk 2,0K Feb  9 11:27 eruption-debug-tool.d
-rwxrwxr-x    2 dirk dirk 5,4M Feb 28 12:23 eruption-gui
-rw-rw-r--    1 dirk dirk 3,3K Feb  9 11:27 eruption-gui.d
-rwxrwxr-x    2 dirk dirk 2,5M Feb 25 14:30 eruption-hotplug-helper
-rw-rw-r--    1 dirk dirk  429 Nov 23 13:49 eruption-hotplug-helper.d
-rwxrwxr-x    2 dirk dirk 3,3M Feb 25 14:30 eruption-hwutil
-rw-rw-r--    1 dirk dirk 1,9K Feb  9 11:27 eruption-hwutil.d
-rwxrwxr-x    2 dirk dirk 4,1M Feb 25 14:31 eruption-netfx
-rw-rw-r--    1 dirk dirk  850 Nov 23 13:49 eruption-netfx.d
-rwxrwxr-x    2 dirk dirk 3,9M Feb 25 14:31 eruption-process-monitor
-rw-rw-r--    1 dirk dirk 1,1K Nov 23 13:49 eruption-process-monitor.d
-rwxrwxr-x    2 dirk dirk 2,6M Feb 25 14:30 eruption-util
-rw-rw-r--    1 dirk dirk  849 Feb  9 11:27 eruption-util.d
drwxrwxr-x    2 dirk dirk 4,0K Mär 23  2021 examples
drwxrwxr-x 6405 dirk dirk 316K Feb 27 14:08 .fingerprint
drwxrwxr-x    2 dirk dirk 4,0K Mär 23  2021 incremental
-rw-rw-r--    1 dirk dirk  857 Feb 25 14:33 liberuption.d
-rw-rw-r--    1 dirk dirk  742 Feb 25 14:33 liberuption_rs.d
-rw-rw-r--    2 dirk dirk 282K Feb 25 14:29 liberuption_rs.rlib
-rwxrwxr-x    2 dirk dirk 251K Feb 25 14:30 liberuption.so
-rw-rw-r--    1 dirk dirk  213 Sep 13 19:04 libprocmon_sys.d
-rw-rw-r--    2 dirk dirk 9,6K Feb 25 14:28 libprocmon_sys.rlib
-rwxrwxr-x    2 dirk dirk 495K Feb 25 14:29 simple
-rw-rw-r--    1 dirk dirk  791 Feb 25 14:33 simple.d`

**Comment by DirkSchueler** [comment]
> > Unit /etc/systemd/system/eruption.service is masked
> 
> To unmask `eruption.service` you may want to run this command:
> 
> ```shell
> sudo systemctl unmask eruption.service && sudo systemctl restart eruption.service
> ```

Done
`sudo systemctl status eruption.service`
shows
`× eruption.service - Linux user-mode input and LED driver for keyboards, mice and other devices
     Loaded: loaded (/lib/systemd/system/eruption.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-02-28 13:42:48 CET; 29s ago
       Docs: man:eruption(8)
             man:eruption.conf(5)
             man:eruptionctl(1)
             man:eruption-netfx(1)
    Process: 86101 ExecStart=/usr/bin/eruption -c /etc/eruption/eruption.conf (code=exited, status=5)
    Process: 86111 ExecStopPost=/usr/bin/rm -f /run/eruption/eruption.pid (code=exited, status=0/SUCCESS)
   Main PID: 86101 (code=exited, status=5)
        CPU: 321ms

Feb 28 13:42:47 inspiron7506 eruption[86101]: inspiron7506 eruption[86101]: To enable this device driver, please change the 'driver_maturity_level' sett>
Feb 28 13:42:47 inspiron7506 eruption[86101]: inspiron7506 eruption[86101]: Not binding the device driver because it would require a lesser code maturit>
Feb 28 13:42:47 inspiron7506 eruption[86101]: inspiron7506 eruption[86101]: To enable this device driver, please change the 'driver_maturity_level' sett>
Feb 28 13:42:47 inspiron7506 eruption[86101]: inspiron7506 eruption[86101]: Not binding the device driver because it would require a lesser code maturit>
lines 1-16...skipping...`

**Comment by X3n0m0rph59** [comment]
@DirkSchueler 

Eruption now filters out unstable drivers in the default configuration. To enable testing or even experimental drivers, please change the respective line in the `[global]` section of `/etc/eruption/eruption.conf`.

The default is: `driver_maturity_level = "stable"`. Valid values are `driver_maturity_level = "testing"` or even `driver_maturity_level = "experimental"`


```toml
# Eruption - Linux user-mode input and LED driver for keyboards, mice and other devices
# Main configuration file

[global]
enable_experimental_features = false
driver_maturity_level = "testing"

profile_dirs = ["/var/lib/eruption/profiles/"]
script_dirs = ["/usr/share/eruption/scripts/"]

# select your keyboard variant
# keyboard_variant = "ANSI"
keyboard_variant = "ISO"

# Mouse handling
enable_mouse = true
grab_mouse = true

# "Away from keyboard" handling
afk_profile = "/var/lib/eruption/profiles/rainbow-wave.profile"
afk_timeout_secs = 0

# [[devices]]
# entry_type = "device"
# device_class = "serial"
# device_name = "Adalight Custom Serial LEDs"
# device_file = "/dev/ttyACM0"

# [[devices]]
# entry_type = "blacklist"
# vendor_id = 0x1e7d
# product_id = 0x311a
```

**Comment by DirkSchueler** [comment]
Setting driver_maturity_level = "experimental" , git pull, make, sudo make install (no errors anymore), make start brought me Roccat Volcano Pro back to light. Thank you so far!

But: I cannot start the eruption gui "Could not start Eruption GUI, is the daemon running?" Reason; The name org.eruption was not provided by any .service files.
