### ISSUE TITLE
Fix AUR Package to not clone from git

### ISSUE THREAD

**Issue by mpldr** [X3n0m0rph59/eruption#123]
**Introduction**

cloning from git leads to most AUR helpers to recognize the package as a development package and trying to update every time it's run, even though the built commit is always the same.

**Please describe the bug**

```
❯ yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 chaotic-aur is up to date
 sublime-text is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Flagged Out Of Date AUR Packages:  aerc-git  android-apktool
:: 2 Packages to upgrade.
2  aur/i2p         1.7.0-1  -> 1.7.0-1
1  devel/eruption  0.1.23-1 -> latest-commit
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
```

As indicated by the `latest-commit` it's detected as a development package

**To Reproduce**

1. install yay
2. `yay -S eruption`
3. `yay` to update all packages
4. see eruption being built again

**Expected behavior**

The package is only recompiled if the version changes.

**Logs**

not applicable

**Please complete the following information:**

 * Eruption version [e.g. 0.1.23]

**Additional context**

Usually compiled-from-source program PKGBUILDS look like this:
```shell
pkgname=screego-server
_pkgname=screego-server
pkgver=1.6.2
pkgrel=1
pkgdesc='screen sharing for developers'
arch=('x86_64' 'arm64')
url="https://github.com/screego/server"
license=('GPL3')
provides=("${pkgname}")
conflicts=("screego-server")
makedepends=('go' 'yarn')
optdepends=('nginx: to allow reverse proxy connections')
source=("$pkgname-$pkgver.tar.gz::$url/archive/v$pkgver.tar.gz"
	"screego-server.service"
	"tmpfiles.conf"
	"sysusers.conf"
)
sha256sums=('08433002a9d0366b3a537c8c7f93bbb797e07234e89d8ae9946bb57894f2495c'
            '7467398db76e4c14f7c4bd402b8dc1dce71866856ac9ae3d54cec6e5ce93155c'
            '1d4494d5328700b304b0837dafc7a5772b8abe3435a0a24337a89f25ad5acd1b'
            '5804e54e4af5704fd5066c45313d7635798bd4389cd8312ee965c911d9d75e85')
```

This way updating the package is also easier by simply setting `pkgver` to the new version and running `updpkgsums` and `mksrcinfo`

**Comment by X3n0m0rph59** [comment]
@mpldr Thank you very much for your contribution! It is much appreciated!
