### ISSUE TITLE
Compiling error on Garuda

### ISSUE THREAD

**Issue by Siiire** [X3n0m0rph59/eruption#150]
I can't compile eruption (non git) from the AUR on Garuda Linux.

For more information about this error, try 'rustc --explain E0310'.
error: could not compile 'wayland-backend' due to 13 previous errors
warning: build failed, waiting for other jobs to finish... 

Let me know if you need any additional info. I am not a dev or really used to Github in general, sorry in advance for any noobiness :) 

EDIT: I can install the git version without any issues however I need to type in 'sudo systemctl enable --now eruption.service' after every reboot because otherwise nothing is working, including the volume controls on the keyboard itself.

**Comment by X3n0m0rph59** [comment]
Hi @Siiire, thanks for reporting this issue!

The build of the `aur/eruption` package (non-git) is broken across all Arch based distros.

**Comment by X3n0m0rph59** [comment]
@Siiire I have just pushed a fix for the build issue to the aur!

Building the `aur/eruption` (non-git) package should now work again.

**Comment by X3n0m0rph59** [comment]
I will close this issue now, please open up a separate issue regarding the problem with the systemd unit!
