### ISSUE TITLE
Missing packages from Ubuntu PPA

### ISSUE THREAD

**Issue by RoggeHaj** [X3n0m0rph59/eruption#190]
**Introduction**
I was really happy to see the release mail for Eruption-0.3.0 and went to update my Ubuntu-22.10 box. However, when trying to fetch new packages I did not receive one for Eruption. No big deal I thought, it will be up sooner than later so in the meantime, I just wanted to check which version I was currently on using the command with response:

```shell
apt list eruption*
Listing... Done
eruption-git/kinetic,now 0.1.23-3-ubuntu1 amd64 [installed]
eruption/kinetic,now 0.1.23-1-ubuntu2 amd64 [residual-config]
```

This is not what I expected since I am fairly sure I've run 0.2.0 (as a git snapshot) previously. 

I did notice that the -git package and the regular package differ in size, but I did not look further into what really differs in the package contents.

**Please describe the bug**
Adding the PPA, and updating the package listing should give, at least,  an installable version 0.2.0 of Eruption. Looking at the PPA contents indicates that packages have not been updated since 2022-03-18 for eruption (_amd64.deb) and 2022-03-05 for eruption-git (_amd64.deb) as depicted in the _Screenshots_  section below.

**To Reproduce**
```shell
sudo add-apt-repository ppa:x3n0m0rph59/eruption
sudo apt update
apt list eruption*
```

**Expected behavior**
The command under _To Reproduce_ should produce output containing (at least) release 0.2.0 and ideally release 0.3.0.

**Screenshots (optional)**
![Screenshot from 2022-11-29 16-48-17](https://user-images.githubusercontent.com/65942062/204582421-48d2bbd0-b3ab-4f53-b270-db7e07e5dc51.png)
![Screenshot from 2022-11-29 16-50-36](https://user-images.githubusercontent.com/65942062/204582443-7a19e860-e422-4f7e-a7d4-44e8bc21c352.png)

**Comment by X3n0m0rph59** [comment]
Hi @RoggeHaj, thanks for reporting this issue!

I have published new packages for `eruption` and `eruption-git` version `0.3.0` on all supported distros.
