### ISSUE TITLE
Brightness Controll doesn't work on Fedora 37

### ISSUE THREAD

**Issue by LukasSchulte1** [X3n0m0rph59/eruption#193]
**Introduction**
Recently updated to Fedora 37 from Fedora 36. I have a Roccat Vulcan 121 AIMO which has a Volume knob that can be used to either control the volume or the brightness of the backlight (There is a button to switch between both modes).

**Please describe the bug**
When I set the knob to brightness control the brightness won't change anymore. Worked on Fedora 36 with version 0.2.
With the update to Fedora 37 the eruption software was updated to 0.3 from 0.2. I think this might be the cause of the problem. 
 

**To Reproduce**

**Expected behavior**
The brightness knob should change the brightness of the backlight

**Logs**
```
Dec 24 13:38:43 fedora.fritz.box systemd[1]: Starting eruption.service - Realtime RGB LED Driver for Linux...
Dec 24 13:38:43 fedora.fritz.box systemd[1]: Started eruption.service - Realtime RGB LED Driver for Linux.
```

**Screenshots (optional)**

**Please complete the following information:**

 * Eruption version [e.g. 0.3.0]
Bus 003 Device 003: ID 1e7d:3098 ROCCAT ROCCAT Vulcan AIMO

**Additional context**

**Comment by X3n0m0rph59** [comment]
Hi @LukasSchulte1, thank you for reporting this issue!

This should be fixed by Eruption `0.3.2`
