### ISSUE TITLE
Windows edition maybe?

### ISSUE THREAD

**Issue by Geistica** [X3n0m0rph59/eruption#33]
Hey I like the idea and it works fine on linux for me. I wish I could use it on windows too tho since there is currently no audio visualizer for windows for said Keyboard. Can you maybe port it over?

**Comment by X3n0m0rph59** [comment]
Hi! Thanks for your request! Porting to Windows would amount to a complete re-implementation of the daemon, except maybe for the Lua scripts. This is currently not planned. Im am not opposed to porting it to Windows, but I don't have the resources right now.
