### ISSUE TITLE
Feature request: Game Mode Configuration

### ISSUE THREAD

**Issue by Madcliff** [X3n0m0rph59/eruption#38]
On I3 the super key is often configured as the modifier key that drives much of the OS. It used to be possible to stop the gaming mode trigger from disabling particular keys, can we please get that functionality back?

**Comment by X3n0m0rph59** [comment]
Hi! Thanks for reporting this issue!
The keyboard hardware will stop sending events for the super key when "game mode" is enabled. This can be worked around by using the USB HID layer though. It should be possible to implement it this way. I will look into this soon!
