### ISSUE TITLE
How to execute a system function from a macro?

### ISSUE THREAD

**Issue by Madcliff** [X3n0m0rph59/eruption#39]
So i recall that it used to be possible to execute a bash command from a macro. What is the correct syntax to do so currently?

**Comment by X3n0m0rph59** [comment]
Hi! Shell commands may be run like this:
```Lua
result = system("/usr/bin/logger", { "-i", "Message from eruption" })
if result ~= 0 then
    error("Command execution failed with result: " .. result)
end
```

The first parameter to the `system` function is the command name, the second parameter is a Lua table (roughly equivalent to an array) that specifies the command line parameters of the program being run.

The program will be executed with the rights of the `eruption` process (root by default).
To run the program as a different user you can do the following:

```Lua
result = system("/usr/bin/sudo", { "DISPLAY=:1", "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus", "-u", "user", "notify-send", "Message", "A message from eruption" })
if result ~= 0 then
    error("Command execution failed with result: " .. result)
end
```

Please replace "user" and "1000" with the respective user name and ID.
