### ISSUE TITLE
Add per-user config directory

### ISSUE THREAD

**Issue by RoggeHaj** [X3n0m0rph59/eruption#42]
I think it would be beneficial if eruption had support for a local user config directory, `${HOME}/.config/eruption`, or similar that would allow overriding the central scripts and config files as well as adding new scripts without having to modify the central files.

**Comment by RoggeHaj** [comment]
*sigh* I really need to improve my reading skills.

**Comment by X3n0m0rph59** [comment]
@RoggeHaj, thanks for your feature request! This has been requested multiple times, and I too think that it would be really nice to have per-user config directories. This feature mainly does not exist at the moment, because of the security implications this has.

Please see issue #27
