### ISSUE TITLE
Eruption fails to start

### ISSUE THREAD

**Issue by LuxLucian** [X3n0m0rph59/eruption#55]
The program fails to start with the following

**Logs**
https://pastebin.com/DwzgTM1d

`sudo systemctl -u eruption.service -b` does not seem to work and returns " systemctl: invalid option -- 'u' "

**Screenshots (optional)**
![slurped-2021-03-18-09:40:31](https://user-images.githubusercontent.com/63475999/111635599-0ca3b480-87ce-11eb-8268-49771e3dfc22.png)

**Please complete the following information:**
 - Eruption version [e.g. 0.1.19]
 - ROCCAT ROCCAT Kone Aimo 16K

**Comment by X3n0m0rph59** [comment]
@LuxLucian Thanks for reporting this issue!

Eruption does not recognize your mouse device (it does not bind the driver to the device). It seems that the USB ID is missing from the list of supported hardware.

Could you please show the output of:

```sh
 $ sudo lsusb
```

The command `sudo systemctl -u eruption.service -b` should read `sudo journalctl -u eruption.service -b`. I've corrected the GitHub issue template. Thanks for bringing this to my attention!

**Comment by X3n0m0rph59** [comment]
The driver for your device was added in the yet to be released version `0.1.20`. Eruption version `0.1.19` does not support this device. Please refer to issue #50 to track the support for your device.

**Comment by X3n0m0rph59** [comment]
I will close this issue now, please post follow-ups via issue #50.
