### ISSUE TITLE
Steam crash eruption-process-monitor

### ISSUE THREAD

**Issue by Elrondo46** [X3n0m0rph59/eruption#69]
**Introduction**
Steam crash eruption-process-monitor

**Please describe the bug**
When switching to Steam window the eruption-process-monitor crash

**To Reproduce**
launch eruption-process-monitor profiles and now switch to Steam Window. And crash

**Expected behavior**
Don't have to crash and better authorize to design a keyboard profile and steam games linked to it

**Logs**
uin 07 17:41:39 eruption-process-monitor[16938]:  INFO  eruption_process_monitor          > Startup completed
juin 07 17:41:39  eruption-process-monitor[16938]: The application panicked (crashed).
juin 07 17:41:39  eruption-process-monitor[16938]: Message:  range end index 4 out of range for slice of length 0

**Screenshots (optional)**

**Please complete the following information:**

 * Eruption version git
 * Your device(s): Bus 001 Device 002: ID 1e7d:3098 ROCCAT ROCCAT Vulcan AIMO

**Comment by X3n0m0rph59** [comment]
Hi @Elrondo46, thank you for reporting this bug!

I was able to reproduce the crash with Steam. The Steam window does not report the associated process' PID. I have updated the code of the `eruption-process-monitor` to not crash when we receive an empty or invalid PID.

The fix will be shipped with Eruption `0.1.22`.
