### ISSUE TITLE
Examples for basic (modifier+key = function) macros

### ISSUE THREAD

**Issue by Bios-Marcel** [X3n0m0rph59/eruption#77]
Hey,

Sorry for bothering in case I've missunderstood something. I've checked user-macros.lua in which a lot oft shift+ macros are defined, there were examples remapping keys and even mouse buttons. But is there are simple way to add a function for something like `Ctrl  Shift 1`.

I've found this example where a function is defined:

```
-- remap the keys 'ü' and '+' to '{' and '}'
-- MACRO_TABLE[68]      = macro_insert_left_curly_bracket   --
-- MACRO_TABLE[74]      = macro_insert_right_curly_bracket  --
```

But this is only a keycode without a modifier. How'd I go about adding a modifier.

**Comment by X3n0m0rph59** [comment]
Hi @Bios-Marcel,

to add one or more modifier keys to a macro invocation you would simply need to inject the respective key down and key up events into the event stream of the `Eruption Virtual Keyboard` device.

Modifier keys and their numeric codes:

| Key | Code |
| ----- | ------- |
| KEY_LEFTCTRL | 29 |
| KEY_LEFTSHIFT | 42 |
| KEY_RIGHTSHIFT | 54 |
| KEY_LEFTALT | 56 |
| KEY_RIGHTCTRL | 97 |
| KEY_RIGHTALT (Alt Gr) | 100 |

Lets say you want to inject the keys `CTRL` + `SHIFT` + `N` when pressing the `CTRL` + `SHIFT` + `1` keys and `CTRL` + `SHIFT` + `N` when pressing just the `2` key:

In your `user-macros.lua` file you would need this:

```Lua
function macro_1(down)
	-- this example transforms CTRL + SHIFT + 1 to CTRL + SHIFT + N

	info("Macros: macro_1")

	-- the key "1" has been pressed, now we need to check the state of the modifier keys
	if modifier_map[LEFT_CTRL] and modifier_map[LEFT_SHIFT] then
		-- if we get here, left SHIFT and CTRL are held down too

		if down then
			-- inject_key(29, true)
			-- inject_key(42, true)

			inject_key(49, true)	-- inject "n"
		else
			inject_key(49, false)	-- inject "n"

			-- inject_key(42, false)
			-- inject_key(29, false)
		end
	else
		-- none of the above conditions are met, so just re-emit the original key event
		inject_key(2, down)	-- inject key "1"
	end
end

function macro_2(down)
	-- this example transforms 2 to CTRL + SHIFT + N

	info("Macros: macro_2")

	-- the key "2" has been pressed
	if down then
		inject_key(29, true)	-- CTRL
		inject_key(42, true)	-- SHIFT

		inject_key(49, true)	-- inject "n"
	else
		inject_key(49, false)	-- inject "n"

		inject_key(42, false)	-- SHIFT
		inject_key(29, false) 	-- CTRL
	end
end

MACRO_TABLE[key_name_to_index("1")] = macro_1
MACRO_TABLE[key_name_to_index("2")] = macro_2
```

**Comment by Bios-Marcel** [comment]
Thanks :)
